_target_: pytorch_lightning.Trainer

# set -1 to train on all GPUs available
# set 0 to train on CPU only
gpus: -1

min_epochs: 1
max_epochs: 400
precision: 32

# prints
# progress_bar_refresh_rate: null
weights_summary: null
# profiler: null


#resume_from_checkpoint: null
