_target_: src.models.moco_model.MoCo


encoder_Q_arch: densenet121
encoder_K_arch: densenet121
K: 2048 #queue size; number of negative keys (default: 65536)
m: 0.999 #momentum (moco) of updating the key encoder
t: 0.07 #softmax temperature
feature_dim: 128
#use_mlp: False #MLP
