# https://wandb.ai (Weights&Biases)

wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: "Barlow_SSL_ImageClef_Final"
    # entity: ""  # set to name of your wandb team or just remove it
    #offline: True  # set True to store all logs only locally
    job_type: "train"
    group: ""
    save_dir: "."
